stages:
    - build
    - test
    - release

# centos6
build_centos:
    stage: build
    tags:
        - centos6
    script:
        - python -m build -vv install
        
test_centos:
    stage: test
    tags:
        - centos6
    script:
        - ./packages/simple_cpp_program
        
release:
    stage: release
    tags:
        - centos6
    script:
        - tar xf out_packages.tar packages
    artifacts:
        paths:
            - out_packages.tar
        expire_in: 1 hour
        
# windows
build_windows:
    stage: build
    tags:
        - windows
    script:
        - python -m build -vv install -M 2012
        
test_windows:
    stage: test
    tags:
        - windows
    script:
        - packages\\simple_cpp_program.exe
        
    
release:
    stage: release
    tags:
        - windows
    script:
        - 7z a out_packages.7z packages
    artifacts:
        paths:
            - out_packages.7z
        expire_in: 1 hour