stages:
    - build
    - test
    
build_centos:
    stage: build
    tags:
        - centos6
    script:
        - python -m build -vv install
    artifacts:
        paths:
            - packages
        expire_in: 10 day
        
test_centos:
    stage: test
    tags:
        - centos6
    script:
        - ./pacages/simple_cpp_program
        
build_windows:
    stage: build
    tags:
        - windows
    script:
        - python -m build -vv install -M 2012
    artifacts:
        paths:
            - packages
        expire_in: 10 day
        
test_windows:
    stage: test
    tags:
        - windows
    script:
        - pacages\\simple_cpp_program.exe
        
    