stages:
    - build
    - test
    
build_linux:
    stage: build
    tags:
        - build_linux
    script:
        - python -m build -vv install
    artifacts:
        paths:
            - packages
        expire_in: 10 day
        
build_windows:
    stage: build
    tags:
        - build_windows
    script:
        - python -m build -vv install -M 2012
    artifacts:
        paths:
            - packages
        expire_in: 10 day
        
test:
    stage: test
    script:
        - cd pacages
        - ./simple_cpp_program
        
    